---
dependency:
  name: galaxy
driver:
  name: docker
lint: |   
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: test-instance-ubuntu
    image: eldius/ubuntu-systemd:latest
    command: /sbin/init
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    env:
      container: docker
provisioner:
  name: ansible
verifier:
  name: testinfra
